package org.mybatis.pojo;

public class Student extends StudentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated Wed Jul 27 22:36:52 CST 2022
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_gender
     *
     * @mbggenerated Wed Jul 27 22:36:52 CST 2022
     */
    private String stuGender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated Wed Jul 27 22:36:52 CST 2022
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated Wed Jul 27 22:36:52 CST 2022
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_gender
     *
     * @return the value of student.stu_gender
     *
     * @mbggenerated Wed Jul 27 22:36:52 CST 2022
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_gender
     *
     * @param stuGender the value for student.stu_gender
     *
     * @mbggenerated Wed Jul 27 22:36:52 CST 2022
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender == null ? null : stuGender.trim();
    }

    @Override
    public String toString() {
        return "Student{" +
                "stuName='" + stuName + '\'' +
                ", stuGender='" + stuGender + '\'' +
                '}';
    }
}